[versions]
kodein          = "7.16.0"
kotlin-wrappers = "1.0.0-pre.504"

[libraries]
kodein-di                        = { module = "org.kodein.di:kodein-di",                           version.ref = "kodein" }
kotlin-wrappers-bom              = { module = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom", version.ref = "kotlin-wrappers" }
kotlin-wrappers-js               = { module = "org.jetbrains.kotlin-wrappers:kotlin-js" }
kotlin-wrappers-react            = { module = "org.jetbrains.kotlin-wrappers:kotlin-react" }
kotlin-wrappers-react-redux      = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-redux" }
kotlin-wrappers-react-router-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-router-dom" }
kotlin-wrappers-styled-next      = { module = "org.jetbrains.kotlin-wrappers:kotlin-styled-next" }
