package io.github.andrewk2112.kjsbox.frontend.buildscript.commongradleextensions.gradle.tasks.actions.writeintodirectory

interface SimpleWriteIntoDirectoryAction : WriteIntoDirectoryAction<Exception>
